export type Restaurant = {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string[];
  cuisine: { id: number; name: string; primary: string }[];
  corkage_fee: boolean;
  dogs_ok: boolean;
  accepts_reservations: boolean;
  accepts_events: boolean;
  price_range_max: number | null;
  price_range_min: number | null;
  location: [number, number];
  city: string;
  state: string;
  country: string;
  address: string;
  locale: [string, string, string];
  phone: string;
  website: string;
  email: string;
  image_url: string;
  image_url_alt: string;
  dap_compliance: string[];
};
